### ISSUE TITLE
Uncaught InvalidArgumentException: uri

### ISSUE THREAD

**Issue by ifdandy** [Yurunsoft/YurunHttp#19]
URL : http://www.31dj.com/

PHP Fatal error:  Uncaught InvalidArgumentException: uri http:// parse error in /www/wwwroot/imi.qq.com/app/vendor/yurunsoft/yurun-http/src/YurunHttp/Http/Psr7/Uri.php:78
Stack trace:
#0 /www/wwwroot/imi.qq.com/app/vendor/yurunsoft/yurun-http/src/YurunHttp/Handler/Swoole/SwooleHttpConnectionPool.php(59): Yurun\Util\YurunHttp\Http\Psr7\Uri->__construct()
#1 /www/wwwroot/imi.qq.com/app/vendor/yurunsoft/yurun-http/src/YurunHttp/Handler/Swoole/SwooleHttpConnectionPool.php(82): Yurun\Util\YurunHttp\Handler\Swoole\SwooleHttpConnectionPool->createConnection()
#2 /www/wwwroot/imi.qq.com/app/vendor/yurunsoft/yurun-http/src/YurunHttp/Handler/Swoole/SwooleHttpConnectionManager.php(86): Yurun\Util\YurunHttp\Handler\Swoole\SwooleHttpConnectionPool->getConnection()
#3 /www/wwwroot/imi.qq.com/app/vendor/yurunsoft/yurun-http/src/YurunHttp/Handler/Swoole.php(264): Yurun\Util\YurunHttp\Handler\Swoole\SwooleHttpConnectionManager->getConnection()
#4 /www/wwwroot/imi.qq.com/app/vendor/yurunsoft/yurun-http/src/YurunHttp/Handler/Swoole.php(418): Yur in /www/wwwroot/imi.qq.com/app/vendor/yurunsoft/yurun-http/src/YurunHttp/Http/Psr7/Uri.php on line 78

请求构建代码：
`
$http = \Yurun\Util\HttpRequest::newSession();
$http->retry(3);
$http->followLocation = true;
$http->maxRedirects = 5;
$http->timeout(30000);
 $http->headers($header);
$response = $http->get($url);
$html = $response->body();
`

**Comment by ifdandy** [comment]
对了，同样的一组url，用guzzle跑是没问题的
